### ISSUE TITLE
Council color palettes

### ISSUE THREAD

**Issue by eroten** [Metropolitan-Council/councilR#15]
There are  Council colors, but what about Council color palettes?

Would work similarly to [wesanderson](https://github.com/karthik/wesanderson), [dutchmasters](https://github.com/EdwinTh/dutchmasters).

See also [Creating corporate colour palettes for ggplot2](https://drsimonj.svbtle.com/creating-corporate-colour-palettes-for-ggplot2)

**Comment by ehesch** [comment]
@eroten does `scale_color_council` and `scale_fill_council` close this issue?

**Comment by eroten** [comment]
Yes! Lets close this one
