### ISSUE TITLE
Unable to install: cannot find function tibble

### ISSUE THREAD

**Issue by ashleyasmus** [Metropolitan-Council/councilR#20]
Maybe 
Installing package into ‘C:/Users/AsmusAL/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'councilR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in tibble(x = c(1:8), y = c(1:8), col = c(1:8)) : 
  could not find function "tibble"

**Comment by eroten** [comment]
Error was addressed #21. Feel free to re-open if not resolved
