### ISSUE TITLE
GIS Library

### ISSUE THREAD

**Issue by leonx075** [Metropolitan-Council/councilR#29]
Cannot use the import GIS Function

![image](https://user-images.githubusercontent.com/20566222/157475543-720b120c-d164-4a71-bf5e-a51770499a3d.png)

**Comment by eroten** [comment]
Could you generate a [reprex](https://reprex.tidyverse.org/) to go with this bug report, please?

**Comment by leonx075** [comment]
Solved:
Requires ODBC to be registered on Windows...
https://metcmn.sharepoint.com/sites/GIS/GIS%20Site%20Pages/Data.aspx
