### ISSUE TITLE
widespread issue with opensource packages

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/councilR#35]
Hi @eroten - I seem to be having a problem with this package. This seems to be a pretty common issue with R packages developed from the ground-up; I found [a much better description here](https://youtu.be/QmepQCumV6A?t=6) than what I could write... Let me know what you think. Maybe @ravenmcknight or @ashleyasmus have some wisdom here too :)

**Comment by ehesch** [comment]
JK - it's just too awesome/helpful of a package! Thanks for all you do for us here @eroten! Happy birthday!!!!!

**Comment by JonathanEhrlichMC** [comment]
The package is amazing! I was expecting a 4/1 prank but this is better. Happy Birthday!

**Comment by eroten** [comment]
Closing this to clean up our Issues. 

Still very, very grateful for this ❤️
