### ISSUE TITLE
geography function ideas

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/councilR#41]
Hey @eroten - 

This is related to #19, and I'm just curious as to if it would be useful to build in *more* tigris functionality? For instance, do you know if people (other than me 😅) ever do any of the following?

- [ ] fetch smaller tigris geographies; tracts, block groups, blocks (if yes --> let's be sure to build in the "year" option from tigris because there are still datasets that use 2010 rather than 2020 census geographies; could make a suite of functions which are `fetch_*_geo()`)
- [ ] overlay CTU boundaries on maps (rather than county boundaries, for instance)
- [ ] apply a *special* theme for simple ggplot2 spatial maps (as in a `theme_council_geo`)
- [ ] add geography labels (for instance, add a word label for each of the counties or ctus which are overlaid)

Let me know if you see a need for any of these things. In thinking about it, I'm pretty excited about the potential of a `theme_council_geo`, but I don't think having anything else as a function would make my workflows easier. HOWEVER, if you and or others are also doing things like this, I think more of these ideas (and maybe more???) would be useful!

**Comment by eroten** [comment]
For example, cities

```r
cities <- tigris::county_subdivisions(
  state = "MN",
  county = c("Anoka", "Carver", "Dakota", "Hennepin", "Ramsey", "Scott", "Washington"),
  class = "sf"
)
```
