### ISSUE TITLE
older releases

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/councilR#43]
Is there any way that older releases of this package can be made available? This would, for instance, allow councilR to work on computers which the users *dont* have admin rights over (and hence must use an older version of R which doesn't support some things). 

To make it work, I think the version of some dependencies would just need to get downgraded:
cli      (3.2.0  
tibble   (3.1.6
rlang    (1.0.2 
proxy    (0.4-26 
e1071    (1.7-9
s2       (1.0.7
Rcpp     (1.0.8.3
classInt (0.4-3 
openssl  (2.0.0  
sp       (1.4-7   
stringi  (1.7.6  
farver   (2.1.0
dplyr    (1.0.8   
sf       (1.0-7 
rgdal    (1.5-31

**Comment by eroten** [comment]
We use GitHub tags to manage releases, so you can install any given release version by adding it to package name string.
 
```r
library(remotes)
install_github("Metropolitan-Council/councilR@v0.1.2")
```

Is there a particular dependency or function giving you problems, @ehesch? Also, some of the dependencies you have listed aren't called by councilR, like `{e1071}` and `{farver}`.

**Comment by ehesch** [comment]
Installing the older version worked perfectly, thanks!
