### ISSUE TITLE
can't build book (ghg.sp.manual) 

### ISSUE THREAD

**Issue by leonx075** [Metropolitan-Council/councilR#44]
When trying to compile the package ghg.sp.manual I get the folllowing error
![image](https://user-images.githubusercontent.com/20566222/189924346-ef70c09f-dc8f-408d-8490-4f97acf9d471.png)

I made sure to download the latest version of councilR

**Comment by eroten** [comment]
Are you certain this is an error with councilR? `check_font_path()` isn't a councilR function.
