### ISSUE TITLE
deploying shiny apps - can't build

### ISSUE THREAD

**Issue by ehesch** [Metropolitan-Council/councilR#54]
When deploying shiny apps with councilR, there are deployment problems. ggspatial in particular seems to be a problem - is there a way to keep the mapping annotations without fully loading the package?

**Comment by eroten** [comment]
Can you provide more detail on the bugs you are encountering? I'm wondering if we can import specific functions from ggspatial and not have the entire package as a depednecy

**Comment by eroten** [comment]
Upstream issue with other spatial package dependencies
